registers:
  - name: voltage_L1_N
    address: 19000
  - name: voltage_L2_N
    address: 19002
  - name: voltage_L3_N
    address: 19004
  - name: current_L1_N
    address: 19012
  - name: current_L2_N
    address: 19014
  - name: current_L3_N
    address: 19016
  - name: active_power_L1_N
    address: 19020
  - name: active_power_L2_N
    address: 19022
  - name: active_power_L3_N
    address: 19024
  - name: reactive_power_L1_N
    address: 19036
  - name: reactive_power_L2_N
    address: 19038
  - name: reactive_power_L3_N
    address: 19040
  - name: power_factor_L1
    address: 19044
  - name: power_factor_L2
    address: 19046
  - name: power_factor_L3
    address: 19048
  - name: grid_frequency
    address: 19050
  - name: total_current
    address: 19018
  - name: total_active_power
    address: 19026
  - name: total_apparent_power
    address: 19034
  - name: total_reactive_power
    address: 19042

chunks:
  - name: voltage_chunk
    start_address: 19000
    count: 6
  - name: current_chunk
    start_address: 19012
    count: 6
